"""
Product Template Model Extension - AI SEO Tools

This module extends the standard Odoo product.template model with AI-powered SEO features:
- AI description generation using GPT-4
- Automatic meta-tag generation (title, description, keywords)
- Multi-language translation with glossary support
- Complete audit trail and generation history
- GDPR-compliant logging

All AI operations are performed through the ai.seo.service model.
"""

import logging
from odoo import models, fields, api, _
from odoo.exceptions import UserError

_logger = logging.getLogger(__name__)


class ProductTemplate(models.Model):
    """
    Product Template Model - AI SEO Enhancement
    
    Extends product.template with AI-powered SEO features for generating
    optimized descriptions, meta-tags, and translations.
    """

    _inherit = 'product.template'

    # ===============================================
    # AI Description Generation Fields
    # ===============================================
    
    technical_specifications = fields.Text(
        string=_('Technical Specifications'),
        help=_('Detailed technical specs for AI description generation'),
    )

    ai_generated_description = fields.Html(
        string=_('AI Generated Description'),
        readonly=True,
        help=_('Description generated by AI'),
    )

    ai_generation_status = fields.Selection(
        selection=[
            ('draft', _('Draft')),
            ('generated', _('Generated')),
            ('error', _('Error')),
        ],
        default='draft',
        readonly=True,
        help=_('Current status of AI generation (Draft/Generated/Error)'),
    )

    ai_description_tone = fields.Selection(
        selection=[
            ('professional', _('Professional')),
            ('casual', _('Casual')),
            ('technical', _('Technical')),
        ],
        default='professional',
        string=_('Description Tone'),
        help=_('Writing style for generated description'),
    )

    ai_description_word_count = fields.Integer(
        string=_('Target Word Count'),
        default=200,
        help=_('Target words for generated description (150-250)'),
    )

    ai_keywords = fields.Char(
        string=_('Keywords for Generation'),
        help=_('Comma-separated keywords to incorporate in description'),
    )

    ai_generated_keywords = fields.Char(
        string=_('Suggested Keywords'),
        readonly=True,
        help=_('Keywords suggested by AI based on content'),
    )

    # ===============================================
    # SEO Meta-Tags Fields
    # ===============================================
    
    meta_title = fields.Char(
        string=_('Meta Title'),
        help=_('SEO meta title for search engines (max 60 chars)'),
    )

    meta_description = fields.Char(
        string=_('Meta Description'),
        help=_('SEO meta description for search results (max 160 chars)'),
    )

    meta_keywords = fields.Char(
        string=_('Meta Keywords'),
        help=_('SEO keywords for search engines (max 200 chars)'),
    )

    # ===============================================
    # Audit and Logging Fields
    # ===============================================
    
    ai_generation_log = fields.Text(
        string=_('Generation Log'),
        readonly=True,
        help=_('Raw AI response and debug information'),
    )

    seo_last_generated = fields.Datetime(
        string=_('Last SEO Generation'),
        readonly=True,
        help=_('Timestamp of last successful generation'),
    )

    def action_generate_ai_description(self):
        """
        Generate SEO description using AI.

        Called by button in product form.
        """
        service = self.env['ai.seo.service']

        for product in self:
            if not product.name:
                raise UserError(_('Product name is required'))

            _logger.info('[SEO-AI] Generating description for product %s', product.name)

            result = service.generate_description(
                product,
                tone=product.ai_description_tone or 'professional',
                word_count=product.ai_description_word_count or 200,
                keywords=[k.strip() for k in (product.ai_keywords or '').split(',') if k.strip()],
            )

            if result['success']:
                product.write({
                    'ai_generated_description': result['description'],
                    'meta_title': result.get('meta_title', ''),
                    'meta_description': result.get('meta_description', ''),
                    'ai_generation_status': 'generated',
                    'seo_last_generated': fields.Datetime.now(),
                    'ai_generation_log': result['raw_response'],
                })

                self.env['seo.ai.history'].create({
                    'product_id': product.id,
                    'action': 'description_generation',
                    'status': 'success',
                    'input_hash': self._hash_input(product.name),
                    'output': result['description'],
                    'user_id': self.env.user.id,
                })

                _logger.info('[SEO-AI] Description generated successfully for %s', product.name)

            else:
                product.write({
                    'ai_generation_status': 'error',
                    'ai_generation_log': result.get('error', 'Unknown error'),
                })

                self.env['seo.ai.history'].create({
                    'product_id': product.id,
                    'action': 'description_generation',
                    'status': 'error',
                    'input_hash': self._hash_input(product.name),
                    'output': result.get('error', ''),
                    'user_id': self.env.user.id,
                })

                raise UserError(_('Description generation failed: %s') % result.get('error', ''))

    def action_translate_descriptions(self):
        """
        Translate descriptions to all active languages.

        Uses glossary if configured.
        """
        service = self.env['ai.seo.service']
        current_lang = self.env.lang

        for product in self:
            for language in self.env['res.lang'].search([('active', '=', True)]):
                if language.code == current_lang:
                    continue

                text_to_translate = product.description or ''
                if not text_to_translate:
                    continue

                glossary_dict = self.env['seo.ai.glossary']._get_glossary_for_language(
                    language.code
                )

                _logger.info(
                    '[SEO-AI] Translating product %s to %s',
                    product.name, language.code
                )

                result = service.translate_text(
                    text=text_to_translate,
                    source_lang=current_lang,
                    target_lang=language.code,
                    glossary=glossary_dict,
                )

                if result['success']:
                    product.with_context(lang=language.code).write({
                        'description': result['translation'],
                    })

                    self.env['seo.ai.history'].create({
                        'product_id': product.id,
                        'action': 'translation',
                        'status': 'success',
                        'input_hash': self._hash_input(text_to_translate),
                        'output': result['translation'],
                        'user_id': self.env.user.id,
                        'target_language': language.code,
                    })

                    _logger.info('[SEO-AI] Translation successful for %s', language.code)

                else:
                    self.env['seo.ai.history'].create({
                        'product_id': product.id,
                        'action': 'translation',
                        'status': 'error',
                        'input_hash': self._hash_input(text_to_translate),
                        'output': result.get('error', ''),
                        'user_id': self.env.user.id,
                        'target_language': language.code,
                    })

                    _logger.warning('[SEO-AI] Translation failed for %s', language.code)

    def action_generate_meta_tags(self):
        """
        Generate SEO meta-tags using AI.
        """
        service = self.env['ai.seo.service']

        for product in self:
            if not product.name:
                raise UserError(_('Product name is required'))

            _logger.info('[SEO-AI] Generating meta-tags for %s', product.name)

            result = service.generate_meta_tags(product)

            if result['success']:
                product.write({
                    'meta_title': result.get('meta_title', ''),
                    'meta_description': result.get('meta_description', ''),
                    'meta_keywords': result.get('meta_keywords', ''),
                    'seo_last_generated': fields.Datetime.now(),
                    'ai_generation_log': result['raw_response'],
                })

                self.env['seo.ai.history'].create({
                    'product_id': product.id,
                    'action': 'meta_tags_generation',
                    'status': 'success',
                    'input_hash': self._hash_input(product.name),
                    'output': f"Title: {result.get('meta_title', '')}, Description: {result.get('meta_description', '')}",
                    'user_id': self.env.user.id,
                })

                _logger.info('[SEO-AI] Meta-tags generated successfully for %s', product.name)

            else:
                self.env['seo.ai.history'].create({
                    'product_id': product.id,
                    'action': 'meta_tags_generation',
                    'status': 'error',
                    'input_hash': self._hash_input(product.name),
                    'output': result.get('error', ''),
                    'user_id': self.env.user.id,
                })

                raise UserError(_('Meta-tags generation failed: %s') % result.get('error', ''))

    def _hash_input(self, text: str) -> str:
        """
        Hash input for privacy (GDPR compliant).

        Args:
            text: Text to hash

        Returns:
            str: SHA256 hash
        """
        import hashlib
        return hashlib.sha256(text.encode()).hexdigest()
