"""
Product Template Model Extension - AI SEO Tools

This module extends the standard Odoo product.template model with AI-powered SEO features:
- AI description generation using GPT-4
- Automatic meta-tag generation (title, description, keywords)
- Multi-language translation with glossary support
- Complete audit trail and generation history
- GDPR-compliant logging

All AI operations are performed through the ai.seo.service model.
"""

import logging
from odoo import models, fields, api, _
from odoo.exceptions import UserError

_logger = logging.getLogger(__name__)


class ProductTemplate(models.Model):
    """
    Product Template Model - AI SEO Enhancement
    
    Extends product.template with AI-powered SEO features for generating
    optimized descriptions, meta-tags, and translations.
    """

    _inherit = 'product.template'

    # ===============================================
    # AI Description Generation Fields
    # ===============================================
    
    technical_specifications = fields.Text(
        string=_('Technical Specifications'),
        help=_('Detailed technical specs for AI description generation'),
    )

    ai_generated_description = fields.Html(
        string=_('AI Generated Description'),
        readonly=True,
        help=_('Description generated by AI'),
    )

    ai_generation_status = fields.Selection(
        selection=[
            ('draft', _('Draft')),
            ('generated', _('Generated')),
            ('error', _('Error')),
        ],
        default='draft',
        readonly=True,
        help=_('Current status of AI generation (Draft/Generated/Error)'),
    )

    ai_description_tone = fields.Selection(
        selection=[
            ('professional', _('Professional')),
            ('casual', _('Casual')),
            ('technical', _('Technical')),
        ],
        default='professional',
        string=_('Description Tone'),
        help=_('Writing style for generated description'),
    )

    ai_description_word_count = fields.Integer(
        string=_('Target Word Count'),
        default=200,
        help=_('Target words for generated description (150-250)'),
    )

    ai_keywords = fields.Char(
        string=_('Keywords for Generation'),
        help=_('Comma-separated keywords to incorporate in description'),
    )

    ai_generated_keywords = fields.Char(
        string=_('Suggested Keywords'),
        readonly=True,
        help=_('Keywords suggested by AI based on content'),
    )

    # ===============================================
    # SEO Meta-Tags Fields
    # ===============================================
    
    meta_title = fields.Char(
        string=_('Meta Title'),
        help=_('SEO meta title for search engines (max 60 chars)'),
    )

    meta_description = fields.Char(
        string=_('Meta Description'),
        help=_('SEO meta description for search results (max 160 chars)'),
    )

    meta_keywords = fields.Char(
        string=_('Meta Keywords'),
        help=_('SEO keywords for search engines (max 200 chars)'),
    )

    description_ecommerce = fields.Html(
        string=_('E-commerce Description'),
        translate=True,
        help=_('Product description for e-commerce websites'),
    )

    # ===============================================
    # Audit and Logging Fields
    # ===============================================
    
    ai_generation_log = fields.Text(
        string=_('Generation Log'),
        readonly=True,
        help=_('Raw AI response and debug information'),
    )

    seo_last_generated = fields.Datetime(
        string=_('Last SEO Generation'),
        readonly=True,
        help=_('Timestamp of last successful generation'),
    )

    def action_generate_ai_description(self):
        """
        Generate SEO description using AI.

        Called by button in product form. Uses GPT-4o-mini to create
        SEO-optimized descriptions based on product tone and keywords.
        Stores result in ai_generated_description field for review before publishing.
        """
        service = self.env['ai.seo.service']
        current_lang = self.env.lang or 'en_US'

        for product in self:
            if not product.name:
                raise UserError(_('Product name is required'))

            _logger.info('[SEO-AI] Generating description for product %s', product.name)

            result = service.generate_description(
                product,
                tone=product.ai_description_tone or 'professional',
                word_count=product.ai_description_word_count or 200,
                keywords=[k.strip() for k in (product.ai_keywords or '').split(',') if k.strip()],
                language=current_lang,
            )

            if result['success']:
                product.write({
                    'ai_generated_description': result['description'],
                    'meta_title': result.get('meta_title', ''),
                    'meta_description': result.get('meta_description', ''),
                    'ai_generation_status': 'generated',
                    'seo_last_generated': fields.Datetime.now(),
                    'ai_generation_log': result['raw_response'],
                })

                self.env['seo.ai.history'].create({
                    'product_id': product.id,
                    'action': 'description_generation',
                    'status': 'success',
                    'input_hash': self._hash_input(product.name),
                    'output': result['description'],
                    'user_id': self.env.user.id,
                })

                _logger.info('[SEO-AI] Description generated successfully for %s', product.name)

            else:
                product.write({
                    'ai_generation_status': 'error',
                    'ai_generation_log': result.get('error', 'Unknown error'),
                })

                self.env['seo.ai.history'].create({
                    'product_id': product.id,
                    'action': 'description_generation',
                    'status': 'error',
                    'input_hash': self._hash_input(product.name),
                    'output': result.get('error', ''),
                    'user_id': self.env.user.id,
                })

                _logger.error('[SEO-AI] Description generation failed for %s: %s', 
                             product.name, result.get('error', ''))
                raise UserError(_('Description generation failed: %s') % result.get('error', ''))

    def action_translate_descriptions(self):
        """
        Translate descriptions to all active languages.

        Uses glossary if configured. Translates from current language to all
        other active languages, preserving brand terms and HTML tags.
        
        KNOWN ISSUE: Translation feature is not yet fully functional.
        The field description_ecommerce must be marked as translatable in the model,
        and the ir.translation system needs proper integration. This is a work-in-progress.
        """
        service = self.env['ai.seo.service']
        current_lang = self.env.lang or 'en_US'
        
        _logger.info('[SEO-AI] Starting translation from language: %s', current_lang)

        for product in self:
            text_to_translate = product.ai_generated_description or product.description_ecommerce or product.description or ''
            if not text_to_translate:
                raise UserError(_('No description to translate. Please generate SEO description first.'))

            _logger.info('[SEO-AI] Text to translate (first 100 chars): %s', text_to_translate[:100])

            target_languages = self.env['res.lang'].search([
                ('active', '=', True),
                ('code', '!=', current_lang)
            ])
            
            _logger.info('[SEO-AI] Found %d target languages', len(target_languages))
            
            if not target_languages:
                raise UserError(_('No other active languages available for translation.'))

            translated_count = 0
            failed_langs = []

            for language in target_languages:
                try:
                    glossary_dict = self.env['seo.ai.glossary']._get_glossary_for_language(
                        language.code
                    )

                    _logger.info(
                        '[SEO-AI] Translating product %s to %s',
                        product.name, language.code
                    )

                    result = service.translate_text(
                        text=text_to_translate,
                        source_lang=current_lang,
                        target_lang=language.code,
                        glossary=glossary_dict,
                    )

                    if result['success']:
                        translation_text = result['translation']
                        _logger.info('[SEO-AI] Got translation for %s: %s...', 
                                    language.code, translation_text[:100])
                        
                        try:
                            existing_trans = self.env['ir.translation'].search([
                                ('type', '=', 'model'),
                                ('name', '=', 'product.template,description_ecommerce'),
                                ('res_id', '=', product.id),
                                ('lang', '=', language.code),
                            ], limit=1)
                            
                            if existing_trans:
                                existing_trans.write({'value': translation_text})
                                _logger.info('[SEO-AI] Updated translation for %s', language.code)
                            else:
                                self.env['ir.translation'].create({
                                    'type': 'model',
                                    'name': 'product.template,description_ecommerce',
                                    'res_id': product.id,
                                    'lang': language.code,
                                    'value': translation_text,
                                })
                                _logger.info('[SEO-AI] Created translation for %s', language.code)
                        except Exception as e:
                            _logger.exception('[SEO-AI] Failed to save translation for %s. This feature requires the description_ecommerce field to be properly configured as translatable', language.code)

                        self.env['seo.ai.history'].create({
                            'product_id': product.id,
                            'action': 'translation',
                            'status': 'success',
                            'input_hash': self._hash_input(text_to_translate),
                            'output': translation_text,
                            'user_id': self.env.user.id,
                            'target_language': language.code,
                        })

                        translated_count += 1
                        _logger.info('[SEO-AI] Translation successful for %s', language.code)

                    else:
                        failed_langs.append(f"{language.name}: {result.get('error', 'Unknown error')}")
                        
                        self.env['seo.ai.history'].create({
                            'product_id': product.id,
                            'action': 'translation',
                            'status': 'error',
                            'input_hash': self._hash_input(text_to_translate),
                            'output': result.get('error', ''),
                            'user_id': self.env.user.id,
                            'target_language': language.code,
                        })

                        _logger.warning('[SEO-AI] Translation failed for %s: %s', language.code, result.get('error', ''))

                except Exception as e:
                    failed_langs.append(f"{language.name}: {str(e)}")
                    _logger.exception('[SEO-AI] Exception translating to %s', language.code)

            if failed_langs:
                error_msg = _('Translated to %d languages, but %d failed:\n%s') % (
                    translated_count, len(failed_langs), '\n'.join(failed_langs)
                )
                raise UserError(error_msg)
            elif translated_count == 0:
                raise UserError(_('Translation failed for all languages.'))
            
            message = _('Successfully translated to %d language(s)') % translated_count
            _logger.info('[SEO-AI] %s', message)

    def action_generate_meta_tags(self):
        """
        Generate SEO meta-tags using AI.

        Generates optimal meta-title (max 60 chars), meta-description (max 160 chars),
        and keywords for search engine optimization. These are critical for Google
        search results appearance and click-through rates.
        
        The generated tags are stored in meta_title, meta_description, and meta_keywords
        fields, which are then displayed in the SERP preview section.
        """
        service = self.env['ai.seo.service']
        current_lang = self.env.lang or 'en_US'

        for product in self:
            if not product.name:
                raise UserError(_('Product name is required'))

            _logger.info('[SEO-AI] Generating meta-tags for %s', product.name)

            result = service.generate_meta_tags(product, language=current_lang)

            if result['success']:
                product.write({
                    'meta_title': result.get('meta_title', ''),
                    'meta_description': result.get('meta_description', ''),
                    'meta_keywords': result.get('meta_keywords', ''),
                    'seo_last_generated': fields.Datetime.now(),
                    'ai_generation_log': result['raw_response'],
                })

                self.env['seo.ai.history'].create({
                    'product_id': product.id,
                    'action': 'meta_tags_generation',
                    'status': 'success',
                    'input_hash': self._hash_input(product.name),
                    'output': f"Title: {result.get('meta_title', '')}, Description: {result.get('meta_description', '')}",
                    'user_id': self.env.user.id,
                })

                _logger.info('[SEO-AI] Meta-tags generated successfully for %s', product.name)

            else:
                self.env['seo.ai.history'].create({
                    'product_id': product.id,
                    'action': 'meta_tags_generation',
                    'status': 'error',
                    'input_hash': self._hash_input(product.name),
                    'output': result.get('error', ''),
                    'user_id': self.env.user.id,
                })

                _logger.error('[SEO-AI] Meta-tags generation failed for %s: %s',
                             product.name, result.get('error', ''))
                raise UserError(_('Meta-tags generation failed: %s') % result.get('error', ''))

    def action_confirm_and_use_content(self):
        """
        Confirm and apply AI-generated content to the product.
        
        Copies AI-generated description to the e-commerce description field
        (description_ecommerce) and publishes on website if available.
        
        Actions performed:
        1. Copy ai_generated_description to description_ecommerce (e-commerce field)
        2. Meta-tags (meta_title, meta_description, meta_keywords) are already set
        3. Publish on website if website module is active
        4. Create audit log entry for GDPR compliance
        
        This is the final step in the content generation workflow - after confirmation,
        the content is live and ready for search engines and customers to see.
        """
        
        for product in self:
            if not product.ai_generated_description:
                raise UserError(_('No AI-generated description to confirm. Please generate one first.'))
            
            _logger.info('[SEO-AI] Confirming content for product %s', product.name)
            
            update_vals = {
                'description_ecommerce': product.ai_generated_description,
            }
            
            website_published = False
            try:
                if self.env['ir.module.module'].search_count([
                    ('name', '=', 'website'),
                    ('state', '=', 'installed')
                ]):
                    update_vals['website_published'] = True
                    website_published = True
                    _logger.info('[SEO-AI] Website module detected, publishing product')
            except:
                _logger.warning('[SEO-AI] Website module not available, skipping publication')
            
            product.write(update_vals)
            
            self.env['seo.ai.history'].create({
                'product_id': product.id,
                'action': 'content_confirmation',
                'status': 'success',
                'input_hash': self._hash_input(product.name),
                'output': f"Description: {len(product.description_ecommerce) if product.description_ecommerce else 0} chars, "
                         f"Meta title: {product.meta_title or 'N/A'}, "
                         f"Published: {website_published}",
                'user_id': self.env.user.id,
            })
            
            _logger.info('[SEO-AI] Content confirmation successful for %s', product.name)

    def _hash_input(self, text: str) -> str:
        """
        Hash input for privacy (GDPR compliant).

        Creates SHA256 hash of text for audit trail storage without
        storing sensitive product information in clear text.

        Args:
            text: Text to hash (e.g., product name)

        Returns:
            str: SHA256 hash hexdigest (64 chars)
        """
        import hashlib
        return hashlib.sha256(text.encode()).hexdigest()
